# Sjednocení dat

In [1]:
import pandas as pd

In [2]:
food_sample_100 = pd.read_csv("food_sample_100.csv")
food_sample_100.head()

    fdc_id        data_type    description  food_category_id publication_date
0  2644829  sub_sample_food   lentils, dry              16.0       2023-10-19
1  2347263  sub_sample_food    heavy cream               1.0       2022-10-28
2  2261954  sub_sample_food  Flour, potato              11.0       2022-04-28
3   321470  sub_sample_food  Salt, Iodized               2.0       2019-04-01
4   322951  sub_sample_food  Hot dogs beef               7.0       2019-04-01

In [3]:
food_other = pd.read_csv("food_other.csv")
food_other.head()

,fdc_id,data_type,description,food_category_id,publication_date
0,1106032,branded_food,"Chicken, FC Beer Battered Boneless Wing Fritte...",NaN,2020-11-13
1,1107191,branded_food,"MARINARA SAUCE, MARINARA",NaN,2020-11-13
2,1107295,branded_food,"ORIGINAL ROUNDS TORTILLA CHIPS, ORIGINAL",NaN,2020-11-13
3,1107475,branded_food,"NACHO QUESO SUPREME DIP, NACHO QUESO SUPREME",NaN,2020-11-13
4,1107528,branded_food,"CLASSIC JUMBO FRANKS, CLASSIC",NaN,2020-11-13

In [5]:
#print(food_sample_100.columns)
#print(food_other.columns)

print(food_sample_100.shape)
print(food_other.shape)

(100, 5)
(9900, 5)

## Udělat ze dvou dataframes jeden

In [ ]:
# SQL UNION
# PANDAS concat()
# ignore_index=True --> aby nebyly duplicitní indexy
food = pd.concat([food_sample_100, food_other], ignore_index=True)
food

,fdc_id,data_type,description,food_category_id,publication_date
0,2644829,sub_sample_food,"lentils, dry",16.0,2023-10-19
1,2347263,sub_sample_food,heavy cream,1.0,2022-10-28
2,2261954,sub_sample_food,"Flour, potato",11.0,2022-04-28
3,321470,sub_sample_food,"Salt, Iodized",2.0,2019-04-01
4,322951,sub_sample_food,Hot dogs beef,7.0,2019-04-01
...,...,...,...,...,...
9995,2661515,branded_food,"CHAI LATTE SUGAR FREE BLACK TEA CONCENTRATE, C...",NaN,2023-10-26
9996,2661730,branded_food,"APPLE BANANA ORGANIC FRUIT POUCHES, APPLE BANANA",NaN,2023-10-26
9997,2661782,branded_food,"SPINACH ORGANIC PUREE, SPINACH",NaN,2023-10-26
9998,2662107,branded_food,LIGHT MOZZARELLA LOW-MOISTURE PART-SKIM STRING...,NaN,2023-10-26
9999,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26

In [8]:
food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fdc_id            10000 non-null  int64
 1   data_type         10000 non-null  object
 2   description       10000 non-null  object
 3   food_category_id  128 non-null    float64
 4   publication_date  10000 non-null  object
dtypes: float64(1), int64(1), object(3)
memory usage: 390.8+ KB

In [9]:
food_nutrient = pd.read_csv("food_nutrient.csv")
food_nutrient.head()

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
0,1106032,1257,NaN,NaN,71.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
1,1107191,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
2,1107295,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
3,1107475,1257,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G
4,1107528,1257,0.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total trans",G

In [14]:
# SQL JOIN
# PANDAS merge()
# https://pesikj.github.io/Visual-JOIN/
food_merged = pd.merge(food, food_nutrient, on="fdc_id", how="inner")
food_merged.shape

(135336, 17)

### Cvičení

#### Značky a výrobci

In [10]:
branded_food = pd.read_csv("branded_food.csv")
branded_food.head()

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
0,1106032,BRAKEBUSH BROTHERS INC.,NaN,NaN,10038034720202,INGREDIENTS: BONELESS CHICKEN BREAST MEAT WITH...,NaN,85.0,g,NaN,Meat/Poultry/Other Animals Prepared/Processed,GDSN,NaN,2020-09-03,2020-11-13,United States,NaN,NaN,NaN,NaN
1,1107191,Mahco Inc,NaN,NaN,877448001674,"TOMATO PUREE (TOMATOES), CARROTS, ONIONS, SUN-...",NaN,125.0,g,NaN,Prepared Pasta & Pizza Sauces,LI,NaN,2020-09-22,2020-11-13,United States,NaN,NaN,NaN,NaN
2,1107295,Hormel Foods Corporation,NaN,NaN,37600665605,MASA FLOUR (GROUND WHITE CORN WITH A TRACE OF ...,NaN,30.0,g,NaN,"Chips, Pretzels & Snacks",LI,NaN,2020-04-08,2020-11-13,United States,NaN,NaN,NaN,NaN
3,1107475,HP Hood LLC,NaN,NaN,73570130330,"CULTURED PASTEURIZED MILK, CREAM AND NONFAT MI...",NaN,31.0,g,NaN,Cheese,LI,NaN,2020-04-08,2020-11-13,United States,NaN,NaN,NaN,NaN
4,1107528,Bar-S Foods Co.,NaN,NaN,15900002115,"MECHANICALLY SEPARATED CHICKEN, WATER, PORK, D...",NaN,56.0,g,NaN,"Sausages, Hotdogs & Brats",LI,NaN,2020-04-08,2020-11-13,United States,NaN,NaN,NaN,NaN

In [12]:
top3_vyrobci = branded_food['brand_owner'].value_counts().head(3)
top3_vyrobci

brand_owner
Wal-Mart Stores, Inc.    219
Target Stores            199
Meijer, Inc.             168
Name: count, dtype: int64

In [13]:
top5_kategorie = branded_food['branded_food_category'].value_counts().head(5)
top5_kategorie

branded_food_category
Popcorn, Peanuts, Seeds & Related Snacks    504
Candy                                       415
Cheese                                      405
Ice Cream & Frozen Yogurt                   310
Cookies & Biscuits                          272
Name: count, dtype: int64

In [40]:
food_merged_brands = pd.merge(
    branded_food,          # levá tabulka
    food_merged,           # pravá tabulka
    left_on="fdc_id",      # klíč v levé tabulce
    right_on="fdc_id"      # klíč v pravé tabulce
)

print("Řádky v food_merged_brands (inner):", food_merged_brands.shape[0])

Řádky v food_merged_brands (inner): 129284

In [41]:
print(food_merged_brands.shape)
print(food_merged.shape)

(129284, 36)
(135336, 17)

In [42]:
food_merged_brands = pd.merge(food_merged, branded_food, right_on="fdc_id", left_on="fdc_id", how="left")
print(food_merged_brands.shape)
print(food_merged.shape)

(135336, 36)
(135336, 17)

#### Přejmenování sloupce

In [43]:
food_merged_brands = food_merged_brands.rename(columns={"name": "nutrient_name"})

#### Odstranění sloupců (bonus)

In [44]:
food_merged_brands = food_merged_brands.drop(columns=["footnote", "min_year_acquired"])

# food_merged_brands = food_merged_brands.drop(columns=['data_points', 'min', 'max', 'median', 'loq', 'min_year_acquired', 'derivation_id', 'footnote', 
#                                                       'publication_date', 'subbrand_name','gtin_upc','ingredients', 'not_a_significant_source_of', 
#                                                       'serving_size','serving_size_unit', 'household_serving_fulltext','data_source', 'package_weight',
#                                                       'modified_date', 'available_date', 'market_country','discontinued_date', 'preparation_state_code', 
#                                                       'trade_channel', 'short_description'])

In [45]:
food_merged_brands.columns

Index(['fdc_id', 'data_type', 'description', 'food_category_id',
       'publication_date', 'nutrient_id', 'amount', 'data_points',
       'derivation_id', 'min', 'max', 'median', 'loq', 'nutrient_name',
       'unit_name', 'brand_owner', 'brand_name', 'subbrand_name', 'gtin_upc',
       'ingredients', 'not_a_significant_source_of', 'serving_size',
       'serving_size_unit', 'household_serving_fulltext',
       'branded_food_category', 'data_source', 'package_weight',
       'modified_date', 'available_date', 'market_country',
       'discontinued_date', 'preparation_state_code', 'trade_channel',
       'short_description'],
      dtype='object')

In [ ]:
# food_merged_brands.to_csv("food_merged_brands_checkpoint.csv")

## Agregace a řazení

In [ ]:
# pokud neproběhly úpravy výše, tak:
# Načteme tabulky o potravinách
food_sample_100 = pd.read_csv("food_sample_100.csv")
food_other = pd.read_csv("food_other.csv")
# Sjednotíme tabulky o potravinách do jedné tabulky food
food = pd.concat([food_sample_100, food_other], ignore_index=True)
# Načteme data o výživných látkách
food_nutrient = pd.read_csv("food_nutrient.csv")
# Propojíme tabulky o potravinách a výživných látkách
food_merged = pd.merge(food, food_nutrient, on="fdc_id")
# Načteme tabulku o značkách potravin
branded_food = pd.read_csv("branded_food.csv")
# Propojíme tabulku o značkách potravin a tabulkou o potravinách a výživných látkách
food_merged_brands = pd.merge(food_merged, branded_food, right_on="fdc_id", left_on="fdc_id", how="left")
# Přejmenujeme sloupec name na nutrient_name
food_merged_brands = food_merged_brands.rename(columns={"name": "nutrient_name"})
# NEPOVINNÝ KROK: Odstraníme nepotřebné sloupce footnote a min_year_acquired
food_merged_brands = food_merged_brands.drop(columns=["footnote", "min_year_acquired"])

In [39]:
food_merged_brands.head()

,fdc_id,data_type,description,food_category_id,publication_date,nutrient_id,amount,data_points,derivation_id,min,...,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
0,2644829,sub_sample_food,"lentils, dry",16.0,2023-10-19,1101,1.58,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2347263,sub_sample_food,heavy cream,1.0,2022-10-28,1258,20.00,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2261954,sub_sample_food,"Flour, potato",11.0,2022-04-28,1102,21.80,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,321470,sub_sample_food,"Salt, Iodized",2.0,2019-04-01,1051,0.69,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,321470,sub_sample_food,"Salt, Iodized",2.0,2019-04-01,1007,98.40,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# podmínka nutrient_name == protein
# kontrola, že podmínka podmínkuje --> food_merged_brands["nutrient_name"] == "Protein"
# food_merged_brands[food_merged_brands["nutrient_name"] == "Protein"]

protein = food_merged_brands[food_merged_brands["nutrient_name"] == "Protein"]

In [ ]:
# protein[["branded_food_category", "amount"]]

protein.groupby("branded_food_category")["amount"].mean()

# df.groupby(dimenzi)[metrika].agg_funkce()

branded_food_category
Alcohol                          0.684000
All Noodles                     11.107368
Baby/Infant  Foods/Beverages     1.140000
Bacon                           45.200000
Bacon, Sausages & Ribs          27.239630
                                  ...
Weight Control                   3.080000
Wholesome Snacks                 1.485645
Yogurt                           5.596461
Yogurt (Perishable)              4.320000
Yogurt/Yogurt Substitutes        5.578333
Name: amount, Length: 193, dtype: float64

In [25]:
# protein.groupby("branded_food_category").agg({"amount": ["mean", "count"],
#                                                 # "dalsi sloupec" : "sum"
#                                                 }
#                                                 )
protein.groupby("branded_food_category").agg(sloupec=("amount", "mean"))

                                sloupec
branded_food_category
Alcohol                        0.684000
All Noodles                   11.107368
Baby/Infant  Foods/Beverages   1.140000
Bacon                         45.200000
Bacon, Sausages & Ribs        27.239630
...                                 ...
Weight Control                 3.080000
Wholesome Snacks               1.485645
Yogurt                         5.596461
Yogurt (Perishable)            4.320000
Yogurt/Yogurt Substitutes      5.578333

[193 rows x 1 columns]

In [ ]:
# protein.groupby("branded_food_category")["amount"].mean().sort_values(ascending=False).head(10)
top_protein = protein.groupby("branded_food_category")["amount"].mean().sort_values(ascending=False).head(10)

"""
pro lepší čitelnost:

proten_agg = protein.groupby("branded_food_category")["amount"].mean()
proten_agg.sort_values(ascending=False).head(10)

"""

# ASC DESC --> (v pandas) není DESC --> ascending=False

branded_food_category
Bacon                                                  45.200000
Green Supplements                                      44.590000
Drinks Flavoured - Ready to Drink                      32.900000
Energy, Protein & Muscle Recovery Drinks               31.831481
Bacon, Sausages & Ribs                                 27.239630
Canned Tuna                                            21.648889
Meat/Poultry/Other Animals  Prepared/Processed         21.522368
Nut & Seed Butters                                     20.651270
Cheese                                                 19.969457
Meat/Poultry/Other Animals – Unprepared/Unprocessed    19.640000
Name: amount, dtype: float64

In [27]:
# dataframe --> potřebuju parametr by
# series --> npotřebuju by

protein.sort_values(by="amount")

,fdc_id,data_type,description,food_category_id,publication_date,nutrient_id,amount,data_points,derivation_id,min,...,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
135287,2661730,branded_food,"APPLE BANANA ORGANIC FRUIT POUCHES, APPLE BANANA",NaN,2023-10-26,1003,0.00,NaN,70.0,NaN,...,Wholesome Snacks,LI,12.68 oz/360 g,2023-09-14,2023-10-26,United States,NaN,NaN,NaN,NaN
135273,2661515,branded_food,"CHAI LATTE SUGAR FREE BLACK TEA CONCENTRATE, C...",NaN,2023-10-26,1003,0.00,NaN,70.0,NaN,...,Other Drinks,LI,32 fl oz/946 mL,2023-09-08,2023-10-26,United States,NaN,NaN,NaN,NaN
39861,1142662,branded_food,MIXOLOGIST DESIGNED WATERMELON MOJITO PREMIUM ...,NaN,2020-11-30,1003,0.00,NaN,70.0,NaN,...,Alcohol,LI,NaN,2019-03-23,2020-11-30,United States,NaN,NaN,NaN,NaN
135168,2660361,branded_food,EXTRA VIRGIN OLIVE OIL,NaN,2023-10-26,1003,0.00,NaN,70.0,NaN,...,Vegetable & Cooking Oils,LI,500 mL/17 fl oz,2023-09-12,2023-10-26,United States,NaN,NaN,NaN,NaN
135154,2660188,branded_food,NONSTICK BAKING COOKING SPRAY,NaN,2023-10-26,1003,0.00,NaN,70.0,NaN,...,Vegetable & Cooking Oils,LI,5 oz/141 g,2023-09-19,2023-10-26,United States,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76949,1747459,branded_food,STRAWBERRY BANANA FLAVORED GOLD STANDARD 100% ...,NaN,2021-03-19,1003,80.00,NaN,70.0,NaN,...,"Energy, Protein & Muscle Recovery Drinks",LI,NaN,2021-01-22,2021-03-19,United States,NaN,NaN,NaN,NaN
109098,2280607,branded_food,BIRTHDAY CAKE FLAVORED GOLD STANDARD 100% ISOL...,NaN,2022-05-23,1003,83.33,NaN,70.0,NaN,...,"Energy, Protein & Muscle Recovery Drinks",LI,1.58 LB/720 G,2022-02-03,2022-05-23,United States,NaN,NaN,NaN,NaN
116143,2399314,branded_food,ORGANIC LONG GRAIN WHITE RICE,NaN,2022-12-22,1003,86.67,NaN,70.0,NaN,...,Rice,LI,25 lbs/11.34 kg,2020-07-20,2022-12-22,United States,NaN,NaN,NaN,NaN
83130,1842352,branded_food,"PEDIATRIC SHAKE BALANCED NUTRITION, VANILLA",NaN,2021-06-25,1003,87.50,NaN,70.0,NaN,...,Powdered Drinks,LI,237 mL,2021-05-05,2021-06-25,United States,NaN,NaN,NaN,NaN
65924,1593315,branded_food,"CHOCOLATE SHAKE, CHOCOLATE",NaN,2021-03-19,1003,87.50,NaN,70.0,NaN,...,"Energy, Protein & Muscle Recovery Drinks",LI,NaN,2018-06-18,2021-03-19,United States,NaN,NaN,NaN,NaN

### Cvičení

#### Lipidy a tuky

In [47]:
food_merged_brands_lipid = food_merged_brands[
    food_merged_brands["nutrient_name"] == "Total lipid (fat)"
]
food_merged_brands_lipid.head(3)

,fdc_id,data_type,description,food_category_id,publication_date,nutrient_id,amount,data_points,derivation_id,min,...,branded_food_category,data_source,package_weight,modified_date,available_date,market_country,discontinued_date,preparation_state_code,trade_channel,short_description
14,335770,agricultural_acquisition,"Beans, Dry, Small Red, 471 (0% moisture)",16.0,2019-04-01,1004,1.26,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2004789,sub_sample_food,"GRAPE JUICE, PURPLE, FROM CONCENTRATE WITH ADD...",9.0,2021-10-15,1004,0.25,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,335751,agricultural_acquisition,"Beans, Dry, Small Red, 646 (0% moisture)",16.0,2019-04-01,1004,1.27,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
food_merged_brands_lipid_agg = food_merged_brands_lipid.groupby(
    "branded_food_category"
)["amount"].mean()

food_merged_brands_lipid_agg.sort_values(ascending=False)

# food_merged_brands_lipid_agg = food_merged_brands_lipid.groupby(
#     "branded_food_category"
# ).agg({"amount": "mean"})

# food_merged_brands_lipid_agg.sort_values(by="amount", ascending=False)

branded_food_category
Oils Edible                                        93.330000
Vegetable & Cooking Oils                           78.012391
Butter & Spread                                    66.552667
Butter/Butter Substitutes                          63.965000
Meat/Poultry/Other Animals – Prepared/Processed    59.520000
                                                     ...
Pickles/Relishes/Chutneys/Olives                    0.000000
Specialty Formula Supplements                       0.000000
Spreads                                             0.000000
Syrups & Molasses                                   0.000000
Water                                               0.000000
Name: amount, Length: 193, dtype: float64

In [ ]:
# series1 = food_merged_brands_lipid_agg.sort_values(ascending=False).head(10)
# series2 = food_merged_brands_protein_agg.sort_values(ascending=False).head(10)

# common_categories = series1.index.intersection(series2.index)
# common_categories

#### Výrobci a kategorie

In [36]:
food_merged_brands.groupby(
    ["brand_owner", "branded_food_category"]
)["fdc_id"].nunique().sort_values(ascending=False)

brand_owner               branded_food_category
Ferrara Candy Company     Candy                              40
CAMPBELL SOUP COMPANY     Prepared Soups                     29
Wells Enterprises, Inc.   Ice Cream & Frozen Yogurt          24
Danone US, LLC            Yogurt                             24
Bimbo Bakeries USA, Inc.  Breads & Buns                      24
                                                             ..
Zachary Confections Inc   Chocolate                           1
ZOUP!                     Canned Soup                         1
ZOLA                      Plant Based Water                   1
A.J. Trucco, Inc.         Pre-Packaged Fruit & Vegetables     1
A. Zerega's Sons Inc      All Noodles                         1
Name: fdc_id, Length: 5892, dtype: int64

#### Hlasy (bonus)

In [52]:
data = pd.read_csv('votes.csv')

#Celkový počet odevzdaných hlasů v jednotlivých letech.
data.groupby('year')['totalvotes'].sum()

#Celkový počet odevzdaných hlasů pro kandidáty a kandidátky jednotlivých stran pro volby v roce 2020.
data[data['year']==2020].groupby('party_detailed')['candidatevotes'].sum().sort_values(ascending=False)

# Celkový počet odevzdaných hlasů pro kandidáty dvou hlavních stran (DEMOCRAT a REPUBLICAN) pro všechny volby od roku 2020.
# actully for now data has only year 2020 (for condition  od roku 2020)
year = 2020
filter = (data['party_detailed'].isin(['DEMOCRAT','REPUBLICAN'])) &  (data['year']>=year)
data[filter].groupby('year')['candidatevotes'].sum().sort_values(ascending=False)

#Celkový počet odevzdaných hlasů pro stát MONTANA pro všechny roky.
data[data['state']=='MONTANA']['candidatevotes'].sum()

np.int64(5194180)

#### Vítězové (bonus)

In [53]:
data["rank"] = data.groupby(["state", "year"])["candidatevotes"].rank(ascending=False)
winners_by_state_2020 = data[(data["rank"]==1) & (data["year"]==2020)][["state", "party_detailed"]]